# 基础设置
title: 空谷悠音-SuperWangCC的博客
email: ddllkl@outlook.com
description: 空谷悠音，轻飘云绕。环谷四山，尽皆传响。君若问我凌云之志，我答君曰势极雄豪。技术是我的理想，认真是我的态度，行动是理想和态度的结合，是成功之门，这就是我的人生观。
github: SuperWangCC
github_description: Hello I'm SuperWangCC.A Chinese developer.

layouts_dir: ./_layouts
future:   true
timezone: Asia/Shanghai
baseurl: ""  
url: "https://www.coioidea.com" # the base hostname & protocol for your site

paginate: 7
paginate_path: "posts/page:num"


# 构建设置
markdown: kramdown
highlighter: pygments
theme: minima
krandown:
  input: GFM
excerpt_separator: "<!-- moremore -->"
gems:
- jekyll-paginate
