# Site Config
title: 碳氧极思——进步的思想者
name: Coioidea
site_name: 碳氧极思
email: ddllkl#outlook.com
description: 空谷悠音，轻飘云绕。环谷四山，尽皆传响。君若问我凌云之志，我答君曰势极雄豪。技术是我的理想，认真是我的态度，行动是理想和态度的结合，是成功之门，这就是我的人生观。
# 分类（第一个用于文章标志，写在md头信息中）
all_cate: [
["study", "学习"],
["dev", "程序猿笔记"],
["tech", "技术圈"],
["book", "读书&人生"],
["acg", "二次元"],
["program","算法与竞赛"]
]

# Personal Config
github: SuperWangCC
github_description: WangCC@Coioidea,一只学生coder党。
weibo: SuperWangCC
layouts_dir: ./_layouts
future:   true
timezone: Asia/Shanghai
baseurl: "" # the subpath of your site, e.g. /blog
url: "127.0.0.1:4000" # the base hostname & protocol for your site

paginate: 5
paginate_path: "posts/page:num"


# Build settings
markdown: kramdown
highlighter: rouge
krandown:
  input: GFM
excerpt_separator: "<!-- moreandmore -->"
plugins:
- jekyll-paginate
- jemoji
